### ISSUE TITLE
Are all files that are currently pushed to npm latest required for consumers?

### ISSUE THREAD

**Issue by IamLizu** [ljharb/qs#518] opened 2024-11-12 20:21 UTC
Perhaps we as consumers of the package do not need all the files pushed in [npm package](https://www.npmjs.com/package/qs?activeTab=code).

**Comment by ljharb** [comment] 2024-11-12 21:18
Yes, you do. `npm explore qs && npm install && npm test` should always work.

Duplicate of #504. Duplicate of #429. Duplicate of #400. Duplicate of #389. Duplicate of #356. Duplicate of #250.

> The only files that currently show up in `npm pack --dry-run` that *could* be excluded are `.github/FUNDING.yml ` - every other file is 100% necessary in the published package.

**Closed by ljharb** 2024-11-12 21:18 UTC
