### ISSUE TITLE
The arrayFormat parameter ignored with a single-element array

### ISSUE THREAD

**Issue by T-PWK** [ljharb/qs#444] opened 2022-06-15 16:32 UTC
The `arrayFormat` parameter seems to be ignored when using a single-element array.
Example:
```js
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })
```
will return `a=b,c` (`a=b%2Cc`), however, when there is a single array element like in the following example:
```js
qs.stringify({ a: ['b'] }, { arrayFormat: 'comma' })
```
the library returns `a[]=b` (`a%5B%5D=b`)

This issue started appearing in the latest version 6.10.5. Version 6.10.3 works as expected.

**Comment by ljharb** [comment] 2022-06-15 16:33
It’s not a bug; it’s intentional. However, it will be put behind an option; duplicate of #442.

**Closed by ljharb** 2022-06-15 16:33 UTC
