### ISSUE TITLE
Option to ignore leading '?' in a search string

### ISSUE THREAD

**Issue by jinalskothari** [ljharb/qs#209] opened 2017-05-14 19:38 UTC
I use react-router. It exposes a `location.search` string property. It includes the '?' character in the search string. I could write some code to remove it before I give to qs to parse; however it would be nice if qs could do that.

The api could look like this 
```javascript
var parsedObj = qs.parse('?itemType=theBest&itemCost=1gazillion', {ignoreLeadingQuestion:true})
assert.notEqual(parsedObj, {'?itemType':'theBest', itemCost:'1gazillion'})
```

**Comment by ljharb** [comment] 2017-05-14 23:14
Duplicate of #177.

**Closed by ljharb** 2017-05-14 23:14 UTC
