### ISSUE TITLE
feature request: support for arrayFormat: 'comma'

### ISSUE THREAD

**Issue by bryanlarsen** [ljharb/qs#219] opened 2017-07-04 14:39 UTC
from the documentation for go-querystring:

Slice and Array values default to encoding as multiple URL values of the same name. Including the "comma" option signals that the field should be encoded as a single comma-delimited value. Including the "space" option similarly encodes the value as a single space-delimited string. Including the "semicolon" option will encode the value as a semicolon-delimited string. Including the "brackets" option signals that the multiple URL values should have "[]" appended to the value name. "numbered" will append a number to the end of each incidence of the value name, example: name0=value0&name1=value1, etc.

The Kubernetes API appears to be using using the comma option, so it'd be nice to get support for that in qs.   Easy enough to work around, so it doesn't bother me enough to actually submit a pull request, but it's definitely a "would be nice".

**Comment by ljharb** [comment] 2017-07-04 18:57
This looks like it might be a duplicate of #112.

**Comment by kmohrf** [comment] 2017-10-18 13:45
I think I’d be nice if arrayFormat would just accept a function. than we can do whatever we want without without adding any more bloat for specialized array formats.

**Comment by ljharb** [comment] 2017-10-19 06:10
@kmohrf that's a very compelling and interesting suggestion. It seems like https://github.com/ljharb/qs/blob/master/lib/stringify.js#L91 could be the callsite, and https://github.com/ljharb/qs/blob/master/lib/stringify.js#L7-L15 are the three implementations for the currently supported formats, and https://github.com/ljharb/qs/blob/master/lib/stringify.js#L165 is where if `arrayFormat` is a function, it'd use that implementation instead of the alternatives.

**Comment by kmohrf** [comment] 2017-10-19 14:16
sounds good to me or was that an invitation to create a pull request? :)

**Comment by michaelblash** [comment] 2018-01-27 04:09
@ljharb I want to implement this feature but I see a flaw in the @kmohrf suggestion. If `arrayFormat` function accepts an array it should apparently return a string. This string is basically a number of pre-encoded values in a specific format, for example joined by commas. Therefore the user would have to implement his own encoding and even if he wants to utilize default encoder he would not be able to do this because the string should never be encoded any more.
For example, I need to encode an array `a: ['б', 'г']` in a comma separated format using a default encoder. I would do it like
```javascript
qs.stringify({ a: ['б', 'г'] }, {
  arrayFormat: inputArray => inputArray.map(
    a => encodeURIComponent(a) // (1)
  ).join(','),
  encoder: a => encodeURIComponent(a) // (2): duplication of (1)
})
```
If the users supplies an encoder function there will be a duplication of code because he wouldn't have an access to encoder from `arrayFormat` function. If he doesn't - then he would not be able to use a default encoder. Both cases are bad.
I think it would be much easier for user to just assign `'commas'` value to `arrayFormat` property. And it would definitely be much easier for developer to implement it. This feature seems to be not completely useless because the comma sign is assumed to have some special meaning in the URI since JS encodeURI() method doesn't encode it. Besides many services' API require using comma separated values when supplying an array e.g. [Sendbird ('user_ids' parameter)](https://docs.sendbird.com/platform#user_3_list_users).
I'd be pleased to implement it.

**Comment by kmohrf** [comment] 2018-01-27 04:57
@michaelblash i don’t see much of a problem. the already existing `arrayPrefixGenerators` are functions and receive a prefix and a key, none of which seem to be an array. instead they just append *something* to the prefix. so `'commas'` would just be `prefix => prefix + ','`. 
i see where you were going with the array though, but even then I don’t expect any complications because either the passed array items are already encoded or the calling function could pass the encoder as a third argument to the `arrayFormat` function to prevent code duplication. 
in any case: nice to hear you tackle this issue. I simply forgot about it after I cheekily placed myself as a potential candidate to submit a pull request :sweat_smile:.

**Comment by ljharb** [comment] 2018-01-27 06:11
I'd be happy to review a PR for either, or both, approaches :-)

**Comment by olegBryukhanov** [comment] 2018-08-29 05:09
@ljharb Are there any changes for this issue? I really need this feature :)

**Comment by ljharb** [comment] 2018-08-29 05:45
@olegBryukhanov https://github.com/ljharb/qs/issues/219#issuecomment-360963451 is still the case

**Comment by Primajin** [comment] 2018-08-30 13:05
So passing in a function from outside is relatively easy - that's #275 
But what function would you pass in there?

We want `{ a: ['b', 'c'] }` to become `a=b,c` rather than `a[0]=b&a[1]=c`, right?
But passing in a function wouldn't really help with that, because it currently runs through every value one by one.

**Closed** 2019-01-31 23:11 UTC
Labels: feature request, question, stringify
