### ISSUE TITLE
Feature request: `depth: false` or `parseDepth: false` for `qs.parse`

### ISSUE THREAD

**Issue by leoyli** [ljharb/qs#261] opened 2018-05-13 19:36 UTC
Similar to the relationship `arrayLimit: 0` and `parseArrays: false`:

```javascript
qs.parse('a[0]=na', { arrayLimit: 0 }) === { a: [ 'na' ] }
qs.parse('a[0]=na', { parseArrays: false }) === { a: { '0': 'na' } }
```
Therefore for this:

```javascript
qs.parse('a[i]=na', { depth: 1 }) === { a: { i: 'na' } }
qs.parse('a[i]=na', { depth: 0 }) === { a: { '[i]': 'na' } }
```

I believe in some scenario, people may want to suppress parse into any depth, i.e.:

```javascript
qs.parse('a[]=na', { depth: false }) === { 'a[0]': 'na' }  // proposed behaviour
```

so that we can expect for any query key, its value will never be an `object` since they are all decoupled,
```javascript
qs.parse('a=A&a[]=na', { depth: false }) === { 'a': 'A', 'a[0]': 'na' }  // proposed behaviour
```

Any opinion?

**Comment by ljharb** [comment] 2018-05-13 20:50
This seems like a duplicate of #246?

**Comment by leoyli** [comment] 2018-05-13 20:56
@ljharb I read that.  It actually not a duplicated since this request added new option instead of modified the current behaviour.  And Indeed `depth: 0` makes no sense to me, but it is consisted with the current logic, and remains the flexibility, which could be a case for people to choose.  Also I think added `false` option should completely turn the depth parsing off, but `0` should behave literally `0`depth.

**Comment by ljharb** [comment] 2018-05-14 02:39
`qs.parse('a[i]=na', { depth: 0 }) === { a: { '[i]': 'na' } }` seems weird to me - zero depth, to me, seems like it would be `{ 'a[0]': 'na' } `.

In other words, I don't think `{ a: { '[i]': 'na' } }` ever makes sense (although I don't want to make a breaking change if I can avoid it)

**Comment by leoyli** [comment] 2018-05-14 02:45
+1, I thought it were working like this way `{ 'a[0]': 'na' }` when I was trying to configuring the parser function in my express app. So I'm wondering if it should be fixed like a bug, or, like what I suggested, introducing another option and have no breaking changes.

**Comment by ljharb** [comment] 2018-05-14 03:19
There's no tests for a depth of 0, at least. Only 1, 5000, and the default of 5.

That said, maybe it'd be better to add support for `false`, and then in the next semver-major, make `0` work like `false`.

**Comment by rentalhost** [comment] 2018-07-31 00:00
Just to who needs that it works like this report expectative:

```js
// Input:         { a: 1, b: { c: 2 } }
// Output (spaced): a = 1 & b[c] = 2 
_.mapKeys(qs.parse(qs.stringify({ data: postData }), { depth: 0 }).data, (v, key) => {
    return key.replace(/^\[(\w+)]/, '$1');
})
```

**Closed** 2019-08-16 23:25 UTC
Labels: enhancement, feature request, help wanted, parse
