### ISSUE TITLE
Query string don't contain empty object

### ISSUE THREAD

**Issue by aight8** [ljharb/qs#164] opened 2016-05-13 10:39 UTC
When I have the following object:
```JS
{
    myObject: {}
}
```

The query string don't contains the myObject.

**Comment by ljharb** [comment] 2016-05-13 14:44
What would you expect the query string to look like? In query strings, there's usually not "empty arrays" or "empty objects" - if it contains nothing, it usually doesn't exist.

**Comment by ljharb** [comment] 2016-07-16 05:44
Closing this, since this seems to be to be working as designed.

**Closed by ljharb** 2016-07-16 05:44 UTC

**Comment by foisonocean** [comment] 2019-07-19 12:22
@ljharb 
Hi, my case is empty objects may appears in an array, which will effect the length of the array.

```js
const obj1 = {query: [{foo: 'bar'}, {}, {bar: 'foo'}]};
console.log(obj1.query.length);
// 3

const query = qs.stringify(obj1);
// query: 'query%5B0%5D%5Bfoo%5D=bar&query%5B2%5D%5Bbar%5D=foo'


const obj2 = qs.parse(query);
// obj2: { query: [ { foo: 'bar' }, { bar: 'foo' } ] }

console.log(obj2.query.length);
// 2
```

In this example, the length is incorrect with the current implementation of `qs`. Is it possible to fix this?

**Comment by ljharb** [comment] 2019-07-19 15:32
I mean, you could fix it by using something other than empty objects to indicate nonexistence?
